# Generated by Django 3.1 on 2020-10-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20201012_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderupdate',
            old_name='time_stamp',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='order_id',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='update_desc',
            field=models.CharField(max_length=5000),
        ),
    ]
